project:
  type: default
  output-dir: docs
  preview:
    browser: true
author:
- "Reimar ZEH"
- "[Lehrstuhl für Kommunikationswissenschaft](https://www.kowi.rw.fau.de)"
date: last-modified
date-format: "DD.MM.YYYY"
editor: source
toc: true
number-sections: true
highlight-style: pygments
theme: cosmo
format:
  html: 
    code-fold: true
    code-overflow: wrap
    html-math-method: katex
    self-contained: true
    page-layout: full
    grid:
      sidebar-width: 100px
      body-width: 1500px
      margin-width: 200px
      gutter-width: 1.5rem
