---
title: "RECODE GLES Panel"
subtitle: "MediaTrust vs AfD Sympathie"
author:
- "Reimar ZEH"
- "[Lehrstuhl für Kommunikationswissenschaft](https://www.kowi.rw.fau.de)"
- "Filename: *Recode ZA6838-ZA7729*"
date: "`r format(Sys.time(), '%m.%d.%Y')`"
editor: source
toc: true
number-sections: true
highlight-style: pygments
theme: cosmo
format:
  html: 
    code-fold: true
    code-overflow: wrap
    html-math-method: katex
    self-contained: true
    page-layout: full
    grid:
      sidebar-width: 100px
      body-width: 1500px
      margin-width: 200px
      gutter-width: 1.5rem
execute: 
  echo: false
  eval: true
  warning: false
editor_options: 
  chunk_output_type: console
---

# Session Setup

## Global settings & Notes

```{r}
rm(list= ls()) # start clean ####
# show chunk outputs in R-Markdown
knitr::opts_chunk$set(echo = TRUE)

# global settings
options(
  scipen = 999, # deactivate scientific notation
  digits = 3, # activate the required number of decimal places
  max.print = 1000000,
  tibble.print_max = 100000,
  tibble.print_min = 100000
)

# setting a seed
set.seed(42)
```

## Load Packages

```{r}
rm(list= ls()) # start clean ####
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sjlabelled,foreign,tidyverse,sjmisc,Hmisc,panelr,gt,gtExtras,
               here,fs,usethis,labelled,janitor,magrittr,qs,tictoc,
               psych,easystats,irr,lavaan,semTools,semPlot,broom,tidySEM)
```

## Prepare Lists

```{r}
DF = list()
```

## Load Data

```{r}
# load(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.Rda"))
# tic()
DF$orgdat = qread(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.qs"))
source(here("script/CLPMulder.R"))
source(here("script/RICLPMulder.R"))
# toc()
```


# Prepare Analysis
## Select Vars
```{r Select and Recode}
DF$semdat = DF$orgdat %>%
  select(ends_with(c("_160p","_430i","_1500","_020","_1130","_1290")) & starts_with(c("kp10","kp12","kp14","kp16")))
head(DF$semdat)
```


## Rename Vars for sem
```{r}
DF$semdat %<>% mutate(across(everything(), ~rec(., rec = "-99:-1=NA;else = copy")))

# DF$semdat %<>% rename(x1 = kp10_160p, x2 = kp12_160p, x3 = kp14_160p, x4 = kp15_160p, x5 = kp16_160p,
#                       y1 = kp10_430i, y2 = kp12_430i, y3 = kp14_430i, y4 = kp15_430i, y5 = kp16_430i)
# DF$semdat %<>% rename(x1 = kp9_160p, x2 = kp10_160p, x3 = kp12_160p, x4 = kp14_160p, x5 = kp15_160p, x6 = kp16_160p)
                      

# y1 = kp9_430i, y2 = kp10_430i, y3 = kp12_430i, y4 = kp14_430i, y5 = kp15_430i, y6 = kp16_430i)
# DF$semdat %<>% rename(z1 = kp15_1500)
```


## Check Correlations
```{r}
DF$semdat %>% 
  psych::cor.plot(.,stars = T)
# DF$semdat %>% select(ends_with(c("_160p","_430i"))) %>% 
#   gather(key, value) %>% drop_na() %>%
#   separate_wider_delim(key, delim = "_", names = c("Welle", "Var")) %>%
#   ggplot(aes(x = value, color = Welle)) +
#   geom_density(adjust = 1.6) +
#   facet_wrap(vars(Var)) +
#   theme_classic()

```

## Check ICC
```{r}
# ICC requires VARs to be numeric, even when they seem to are numeric -> mutate!

DF$semdat %>% 
  select(ends_with("_160p")) %>% irr::icc()
DF$semdat %>% 
  select(ends_with("_430i")) %>% irr::icc()
DF$semdat %>% 
  select(ends_with("_1500")) %>% irr::icc()
DF$semdat %>% 
  select(ends_with("_020")) %>% irr::icc()
DF$semdat %>% 
  select(ends_with("_1130")) %>% irr::icc()
DF$semdat %>% 
  select(ends_with("_1290")) %>% irr::icc()
```

# SEM
## Estimate Models
```{r Media Trust}
DF$semtemp = DF$semdat %>% select(ends_with(c("_160p","_430i"))) %>% 
  rename(x1 = kp10_160p, x2 = kp12_160p, x3 = kp14_160p,
         y1 = kp10_430i, y2 = kp12_430i, y3 = kp14_430i)
tic()
DF$lv_mod$cl$mt3c <- lavaan(DF$modef$cl$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$cl$mt3u <- lavaan(DF$modef$cl$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$mt3c <- lavaan(DF$modef$ri$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$mt3u <- lavaan(DF$modef$ri$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
toc()
```

```{r Democrazy}
DF$semtemp = DF$semdat %>% select(ends_with(c("_020","_430i"))) %>% 
  rename(x1 = kp10_020, x2 = kp12_020, x3 = kp14_020,
         y1 = kp10_430i, y2 = kp12_430i, y3 = kp14_430i)
tic()
DF$lv_mod$cl$dz3c <- lavaan(DF$modef$cl$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$cl$dz3u <- lavaan(DF$modef$cl$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$dz3c <- lavaan(DF$modef$ri$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$dz3u <- lavaan(DF$modef$ri$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
toc()
```

```{r Migration}
DF$semtemp = DF$semdat %>% select(ends_with(c("_1130","_430i"))) %>% 
  rename(x1 = kp10_1130, x2 = kp12_1130, x3 = kp14_1130,
         y1 = kp10_430i, y2 = kp12_430i, y3 = kp14_430i)
tic()
DF$lv_mod$cl$mg3c <- lavaan(DF$modef$cl$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$cl$mg3u <- lavaan(DF$modef$cl$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$mg3c <- lavaan(DF$modef$ri$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$mg3u <- lavaan(DF$modef$ri$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
toc()
```

```{r Klima}
DF$semtemp = DF$semdat %>% select(ends_with(c("_1290","_430i"))) %>% 
  rename(x1 = kp10_1290, x2 = kp12_1290, x3 = kp14_1290,
         y1 = kp10_430i, y2 = kp12_430i, y3 = kp14_430i)
tic()
DF$lv_mod$cl$cc3c <- lavaan(DF$modef$cl$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$cl$cc3u <- lavaan(DF$modef$cl$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$cc3c <- lavaan(DF$modef$ri$m3c, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
DF$lv_mod$ri$cc3u <- lavaan(DF$modef$ri$m3u, data=DF$semtemp, missing="ML", estimator = "MLR", meanstructure = T, int.ov.free = T)
toc()
```


## Compare Model Fit
```{r Model fit}
CL_Modell = c("MT CLPM fixed","MT CLPM free","Dem CLPM fixed","Dem CLPM free","Mig CLPM fixed","Mig CLPM free","Cli CLPM fixed","Cli CLPM free")
RI_Modell = c("MT RI-CLPM fixed","MT RI-CLPM free","Dem RI-CLPM fixed","Dem RI-CLPM free","Mig RI-CLPM fixed","Mig RI-CLPM free","Cli RI-CLPM fixed","Cli RI-CLPM free")
map(DF$lv_mod$cl, broom::glance) %>% list_rbind() %>% select(c(cfi,tli,agfi,rmsea,srmr,AIC,BIC)) %>% cbind(CL_Modell,.) %>% 
  gt %>%
  fmt_number(decimals = 3, columns = c(cfi,tli,agfi,rmsea,srmr)) %>% gt_theme_nytimes()
map(DF$lv_mod$ri, broom::glance) %>% list_rbind() %>% select(c(cfi,tli,agfi,rmsea,srmr,AIC,BIC)) %>% cbind(RI_Modell,.) %>% 
  gt %>%
    fmt_number(decimals = 3, columns = c(cfi,tli,agfi,rmsea,srmr)) %>% gt_theme_nytimes()

```

## Graphs
```{r Prepare Graphs}
DF$cl_layout = openxlsx::read.xlsx(here("script/Clpm_t6_layout.xlsx")) %>%
  mutate(across(everything(), ~rec(., rec = "-99=NA;else = copy")))
DF$RI_layout = openxlsx::read.xlsx(here("script/RI-clpm_t6_layout.xlsx")) %>%
  mutate(across(everything(), ~rec(., rec = "-99=NA;else = copy")))

cl_graph_list <- map(DF$lv_mod$cl, function(model) {
  prepare_graph(model, layout = DF$cl_layout) %>%
    edit_graph({label_location = 0.8}, element = "edges") %>%
    edit_graph({ label = paste(est_sig_std)}, element="edges")
})  
ri_graph_list <- map(DF$lv_mod$ri, function(model) {
  prepare_graph(model, layout = DF$RI_layout) %>%
    edit_graph({label_location = 0.8}, element = "edges") %>%
    edit_graph({ label = paste(est_sig_std)}, element="edges")
})  
```
```{r}
#| output: asis
map(ri_graph_list, plot)
```
