---
title: "RICLPM GLES Panel"
subtitle: "Internet & Gespräche 2021"
author:
- "Reimar ZEH"
- "[Lehrstuhl für Kommunikationswissenschaft](https://www.kowi.rw.fau.de)"
- "Filename: *Recode ZA6838-ZA7729*"
date: "`r format(Sys.time(), '%m.%d.%Y')`"
editor: source
toc: true
number-sections: true
highlight-style: pygments
theme: cosmo
format:
  html: 
    code-fold: true
    code-overflow: wrap
    html-math-method: katex
    self-contained: true
execute: 
  echo: false
  eval: true
  warning: false
editor_options: 
  chunk_output_type: console
---

# Session Setup

## Global settings & Notes

```{r}
rm(list= ls()) # start clean ####
# show chunk outputs in R-Markdown
knitr::opts_chunk$set(echo = TRUE)

# global settings
options(
  scipen = 999, # deactivate scientific notation
  digits = 3, # activate the required number of decimal places
  max.print = 1000000,
  tibble.print_max = 100000,
  tibble.print_min = 100000
)

# setting a seed
set.seed(42)
```

## Load Packages

```{r}
rm(list= ls()) # start clean ####
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sjlabelled,foreign,tidyverse,sjmisc,Hmisc,flextable,
               here,fs,usethis,labelled,janitor,magrittr,qs,tictoc,
               psych,easystats,irr,lavaan,semTools,semPlot,broom)
```

## Prepare Lists

```{r}
DF = list()
```

## Load Data

```{r}
# load(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.Rda"))
# tic()
DF$orgdat = qread(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.qs"))
source(here("script/models.R"))
# toc()
```


# Prepare Analysis
## Select Vars
```{r}
DF$semdat_3 = DF$orgdat %>% select(contains(c("_1600","_1933")) & !ends_with("flag") & starts_with(c("kp17","kp18","kp19","kp20"))) 

DF$semdat_3_long = DF$semdat_3 %>% pivot_longer(cols = everything(), names_to = c("set",".value"), names_sep = "_")
names(DF$semdat_3_long) = c("Welle","m","w")
head(DF$semdat_3_long)

```

## Check FRQ

```{r}
# tic()

DF$semdat_3 %>% summary(.,maxsum = 20) %>% knitr::kable() 
# toc()
```


## Check Correlations
```{r}
DF$semdat_3 %>% mutate(across(everything(), ~rec(., rec = "-99,-97,-95,-93,-92=NA;else = copy"))) %>%
  psych::cor.plot(.,stars = T)

DF$semdat_3 %>% mutate(across(everything(), ~rec(., rec = "-99,-95,-93,-92=NA;else = copy"))) %>% 
  psych::corr.test()

DF$semdat_3_long %>% select(!"Welle") %>% 
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93,-92=NA;else = copy"))) %>% 
  psych::corr.test()
DF$semdat_3 %>% mutate(across(everything(), ~rec(., rec = "-99,-97,-95,-93,-92=NA;else = copy"))) %>%
  gather(key, value) %>% separate_wider_delim(key, delim = "_", names = c("Welle", "Var")) %>%
  ggplot(aes(x = value, color = Welle)) +
  geom_density(adjust = 1.6) + 
  facet_wrap(vars(Var)) + 
  theme_classic()
```

## Check ICC
```{r}
# ICC requires VARs to be numeric, even when they seem to are numeric -> mutate!

DF$semdat_3 %>% select(contains(c("_1600"))) %>% 
                         mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA; else = copy"))) %>% irr::icc()
DF$semdat_3 %>% select(contains(c("_1933"))) %>% 
                         mutate(across(everything(), ~rec(., rec = "-99,-97,-95,-93,-92=NA; else = copy"))) %>% irr::icc()

```


# SEM
## Prepare VARS
```{r}
DF$semdat_3 %<>% mutate(across(everything(), ~rec(., rec = "-99,-95,-93,-92=NA;else = copy")))
names(DF$semdat_3)<- c("m1", "m2", "m3","m4", "w1", "w2", "w3","w4")
```

```{r}
#| include: false
DF$semdat_3_long = DF$semdat_3 %>% pivot_longer(cols = everything(), cols_vary = "slowest", names_to = c(".value","set"), names_pattern = "(.)(.)")

DF$semdat_3_long %>% select(!"set") %>% psych::corr.test()


```

## CLPM Latent
```{r}
DF$.int_smL.fit <- lavaan::sem(DF$clpm_L4, data=DF$semdat_3, missing="ML", estimator = "MLR", mimic="Mplus", meanstructure = "default")
broom::glance(DF$.int_smL.fit) %>% select(., c(cfi,tli,agfi,rmsea,srmr,AIC,BIC)) %>% mutate(across(where(is.double), round, 3))
broom::tidy(DF$.int_smL.fit) %>% filter(., label!="") %>% mutate(across(where(is.double), round, 3)) %>% 
  select(., c(term, label, op, estimate,std.error,p.value,std.all)) %>% 
  flextable() %>% theme_zebra() %>% 
  color(., i = ~ p.value < 0.05,j = ~ term + p.value + std.all, color="blue") %>%
  bold(., i = ~ p.value < 0.05 & op == "~",j = ~ term + p.value + std.all, bold=T) %>% autofit()
semPaths(DF$.int_smL.fit, what = "std", whatLabels="std", layout="tree2", intercepts = F, residuals = T, structural = T, 
         curvePivot = T, style="mx", rotation = 2, fade = F, edge.label.cex=0.7, edge.label.position = 0.4)
title("BTW21 Internet/Gespräche")
```

## RI-CLPM
```{r}
#| warning: false
tic()
DF$.int_smR.fit <- lavaan::sem(DF$riclpm4, data=DF$semdat_3, missing="ML", estimator = "MLR", mimic="Mplus", meanstructure = "default")
broom::glance(DF$.int_smR.fit) %>% select(., c(cfi,tli,agfi,rmsea,srmr,AIC,BIC)) %>% mutate(across(where(is.double), round, 3))
broom::tidy(DF$.int_smR.fit) %>% filter(., label!="") %>% mutate(across(where(is.double), round, 3)) %>% 
  select(., c(term, label, op, estimate,std.error,p.value,std.all)) %>% 
  flextable() %>% theme_zebra() %>% 
  color(., i = ~ p.value < 0.05,j = ~ term + p.value + std.all, color="blue") %>%
  bold(., i = ~ p.value < 0.05 & op == "~",j = ~ term + p.value + std.all, bold=T) %>% autofit()
semPaths(DF$.int_smR.fit, what = "std", whatLabels="std", layout="tree2", intercepts = F, residuals = T, structural = T, 
         curvePivot = T, style="mx", rotation = 2, fade = F, edge.label.cex=0.7, edge.label.position = 0.4)
title("BTW21 Internet/Social Media")
toc()
```



## Save DATA, if neccessary
```{r}
#| include: false
# DF %>% qsave(., file = paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/text.qs"))
```
