---
title: "RECODE GLES Panel"
subtitle: "HRS: Survey"
author:
- "Reimar ZEH"
- "[Lehrstuhl für Kommunikationswissenschaft](https://www.kowi.rw.fau.de)"
- "Filename: *Recode ZA6838-ZA7729*"
date: "`r format(Sys.time(), '%m.%d.%Y')`"
format: html
editor: source
toc: true
number-sections: true
highlight-style: pygments
theme: cosmo
format:
  html: 
    code-fold: true
    code-overflow: wrap
    html-math-method: katex
    self-contained: true
editor: visual
execute: 
  echo: false
  eval: true
editor_options: 
  chunk_output_type: console
---

# Session Setup

## Global settings & Notes

```{r}
rm(list= ls()) # start clean ####
# show chunk outputs in R-Markdown
knitr::opts_chunk$set(echo = TRUE)

# global settings
options(
  scipen = 999, # deactivate scientific notation
  digits = 3, # activate the required number of decimal places
  max.print = 1000000,
  tibble.print_max = 100000,
  tibble.print_min = 100000
)

# setting a seed
set.seed(42)
```

## Load Packages

```{r}
  rm(list= ls()) # start clean ####
if (!require("pacman")) install.packages("pacman")
pacman::p_load(sjlabelled,foreign,tidyverse,sjmisc,Hmisc,flextable,
               here,fs,usethis,labelled,janitor,magrittr,qs,tictoc,
               psych,easystats,irr,lavaan,semTools,semPlot,broom)
```

## Prepare Lists

```{r}
DF = list()
```

## Load Data

```{r}
# load(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.Rda"))
# tic()
DF$orgdat = qread(paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/za6838_7729.qs"))
source(here("script/models.R"))
# toc()
```

## Check FRQ

```{r}
# tic()
DF$orgdat %>% select(starts_with(c("kp17","kp18","kp19"))) %>% select(contains(c("_1600","_1610"))) %>% frq
DF$orgdat %>% select(contains("_1610")) %>% frq
DF$orgdat %>% select(contains("kp19_1615")) %>% frq
DF$orgdat %>% select(contains("_1632")) %>% frq
DF$orgdat %>% select(contains("_1631")) %>% frq
DF$orgdat %>% select(contains("_1933")) %>% frq
DF$orgdat %>% select(contains("_4043")) %>% frq
DF$orgdat %>% select(contains("_4046")) %>% frq
DF$orgdat %>% select(contains("_2880bo")) %>% frq
DF$orgdat %>% select(contains("_1570g")) %>% frq
DF$orgdat %>% select(contains("19_2880")) %>% frq
DF$orgdat %>% select(contains("_1616A")) %>% frq
DF$orgdat %>% select(contains("_1800")) %>% frq
# toc()
```


## Check Correlations
```{r}
DF$orgdat %>% select(starts_with(c("kp17","kp18","kp19"))) %>% select(contains(c("_1600","_1610"))) %>%
  mutate(across(everything(), ~rec(., rec = "-99,-97,-95,-93=NA;else = copy"))) %>%
  psych::cor.plot(.,stars = T)

DF$orgdat %>% select(starts_with(c("kp17","kp18","kp19"))) %>% select(contains(c("_1600","_1610"))) %>%
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA;-97=1;else = copy"))) %>% 
  psych::corr.test()
```

## Check ICC
```{r}
# ICC requires VARs to be numeric, even when they seem to are numeric -> mutate!

DF$orgdat %>% select("kp17_1600","kp18_1600","kp19_1600") %>%
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA; else = copy"))) %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
  psych::ICC()
DF$orgdat %>% select("kp17_1600","kp18_1600","kp19_1600") %>%
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA; else = copy"))) %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
  irr::icc()
DF$orgdat %>% select("kp17_1610","kp18_1600","kp19_1610") %>%
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA; -97=1;else = copy"))) %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
  irr::icc()

```


## Recode

```{r}
DF$orgdat %<>% mutate(across(contains("_4046"), ~rec(., rec = "-99,-95,-93=NA; else = copy"))) %>% 
  mutate(across(contains("_4046"), ~as.numeric(.)))
DF$orgdat %<>% mutate(across(contains("_4046"), ~rec(., rec = "-99,-95,-93=NA; else = copy"))) 

DF$orgdat %<>% mutate(across(contains("_1570"), ~rec(., rec = "-99,-95,-93=NA; else = copy")))

DF$orgdat %>% select(ends_with("_1570g")) %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
  psych::ICC(.)
DF$orgdat %>% select(ends_with("_1570g")) %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
 irr::icc(.)

DF$orgdat %>% select("kp15_4046","kp19_4046","kp23_4046") %>% 
  mutate(across(everything(), ~as.numeric(.))) %>%
  psych::ICC()
DF$orgdat %>% select(contains("_4046")) %>% psych::corr.test()
```

## CLPM
```{r}
DF$int_sm = DF$orgdat %>% select(starts_with(c("kp17","kp18","kp19"))) %>% select(contains(c("_1600","_1610"))) %>%
  mutate(across(everything(), ~rec(., rec = "-99,-95,-93=NA;-97=1;else = copy")))
names(DF$int_sm)<- c("w1_med", "w2_med", "w3_med", "w1_wis", "w2_wis", "w3_wis")
DF$.int_sm.fit <- lavaan::sem(DF$clpm, data=DF$int_sm, missing="ML", estimator = "MLR", mimic="Mplus", meanstructure = "default")
broom::glance(DF$.int_sm.fit) %>% select(., c(cfi,tli,agfi,rmsea,srmr,AIC,BIC)) %>% mutate(across(where(is.double), round, 3))
broom::tidy(DF$.int_sm.fit) %>% filter(., label!="") %>% mutate(across(where(is.double), round, 3)) %>% 
  select(., c(term, label, op, estimate,std.error,p.value,std.all)) %>% 
  flextable() %>% theme_zebra() %>% 
  color(., i = ~ p.value < 0.05,j = ~ term + p.value + std.all, color="blue") %>%
  bold(., i = ~ p.value < 0.05 & op == "~",j = ~ term + p.value + std.all, bold=T) %>% autofit()
semPaths(DF$.int_sm.fit, what = "std", whatLabels="std", layout="tree2", intercepts = F, residuals = T, structural = F, 
         curvePivot = T, style="mx", rotation = 2, fade = F, edge.label.cex=0.7, edge.label.position = 0.4)
title("BTW21 Internet/Social Media")


```

## Save DATA, if neccessary

```{r}
DF %>% qsave(., file = paste0(Sys.getenv("FAUBOX"),"/GLES/za6838/text.qs"))
```
